export const Products = [
  {
    "productId": "DEV-001",
    "name": "Photon Lite 15 Pro",
    "brand": "Photon",
    "category": "Smartphone",
    "imageUrl": "https://picsum.photos/seed/device01/512/512",
    "description": "6.5-inch OLED smartphone with triple camera and 5G connectivity for everyday productivity and entertainment.",
    "rating": 4.6,
    "price": 899.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-002",
    "name": "Nova Max X",
    "brand": "Nova",
    "category": "Smartphone",
    "imageUrl": "https://picsum.photos/seed/device02/512/512",
    "description": "Flagship Android phone with a high-refresh AMOLED display and fast charging for power users.",
    "rating": 4.5,
    "price": 799.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-003",
    "name": "Auralink WHX-500",
    "brand": "Auralink",
    "category": "Headphones",
    "imageUrl": "https://picsum.photos/seed/device03/512/512",
    "description": "Wireless noise-cancelling over-ear headphones with 30-hour battery life and multipoint Bluetooth.",
    "rating": 4.7,
    "price": 249.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-004",
    "name": "Auralink Buds S",
    "brand": "Auralink",
    "category": "Earbuds",
    "imageUrl": "https://picsum.photos/seed/device04/512/512",
    "description": "Compact true wireless earbuds with active noise cancellation and wireless charging case.",
    "rating": 4.3,
    "price": 129.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-005",
    "name": "Skytype MX Keyboard",
    "brand": "Skytype",
    "category": "Keyboard",
    "imageUrl": "https://picsum.photos/seed/device05/512/512",
    "description": "Low-profile wireless keyboard with backlit keys and multi-device pairing.",
    "rating": 4.4,
    "price": 99.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-006",
    "name": "Skytype Pro Mouse",
    "brand": "Skytype",
    "category": "Mouse",
    "imageUrl": "https://picsum.photos/seed/device06/512/512",
    "description": "Ergonomic wireless mouse with adjustable DPI and silent clicks for office use.",
    "rating": 4.5,
    "price": 59.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-007",
    "name": "Vertex 14 Ultrabook",
    "brand": "Vertex",
    "category": "Laptop",
    "imageUrl": "https://picsum.photos/seed/device07/512/512",
    "description": "14-inch lightweight laptop with all-day battery and SSD storage for students and professionals.",
    "rating": 4.4,
    "price": 1199.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-008",
    "name": "Vertex Studio 16",
    "brand": "Vertex",
    "category": "Laptop",
    "imageUrl": "https://picsum.photos/seed/device08/512/512",
    "description": "16-inch creator laptop with dedicated graphics for video editing and 3D workloads.",
    "rating": 4.5,
    "price": 1899.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-009",
    "name": "ClarityView 27 4K",
    "brand": "ClarityView",
    "category": "Monitor",
    "imageUrl": "https://picsum.photos/seed/device09/512/512",
    "description": "27-inch 4K IPS monitor with thin bezels and HDR support for sharp visuals.",
    "rating": 4.6,
    "price": 399.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-010",
    "name": "ClarityView 34 UltraWide",
    "brand": "ClarityView",
    "category": "Monitor",
    "imageUrl": "https://picsum.photos/seed/device10/512/512",
    "description": "34-inch ultrawide monitor with 144 Hz refresh rate for immersive multitasking and gaming.",
    "rating": 4.5,
    "price": 699.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-011",
    "name": "SnapCam V200",
    "brand": "SnapCam",
    "category": "Webcam",
    "imageUrl": "https://picsum.photos/seed/device11/512/512",
    "description": "1080p webcam with dual microphones and auto light correction for video calls.",
    "rating": 4.2,
    "price": 69.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-012",
    "name": "SnapCam Stream 4K",
    "brand": "SnapCam",
    "category": "Webcam",
    "imageUrl": "https://picsum.photos/seed/device12/512/512",
    "description": "4K streaming webcam with adjustable field of view and background blur.",
    "rating": 4.4,
    "price": 149.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-013",
    "name": "PulseBar Sound 2.1",
    "brand": "PulseBar",
    "category": "Speaker",
    "imageUrl": "https://picsum.photos/seed/device13/512/512",
    "description": "Compact soundbar with wireless subwoofer for clear TV audio and music.",
    "rating": 4.3,
    "price": 229.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-014",
    "name": "PulseBar Mini",
    "brand": "PulseBar",
    "category": "Speaker",
    "imageUrl": "https://picsum.photos/seed/device14/512/512",
    "description": "Portable Bluetooth speaker with water resistance and 12-hour battery life.",
    "rating": 4.4,
    "price": 79.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-015",
    "name": "FluxCharge 20K",
    "brand": "FluxTech",
    "category": "Power Bank",
    "imageUrl": "https://picsum.photos/seed/device15/512/512",
    "description": "20,000 mAh power bank with 65 W USB-C PD for laptops, tablets, and phones.",
    "rating": 4.6,
    "price": 89.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-016",
    "name": "FluxCharge Mini 10K",
    "brand": "FluxTech",
    "category": "Power Bank",
    "imageUrl": "https://picsum.photos/seed/device16/512/512",
    "description": "10,000 mAh slim power bank with fast charging and pass-through support.",
    "rating": 4.3,
    "price": 49.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-017",
    "name": "Nimbus AX3000 Router",
    "brand": "Nimbus",
    "category": "Networking",
    "imageUrl": "https://picsum.photos/seed/device17/512/512",
    "description": "Wi‑Fi 6 dual-band router with MU-MIMO for smooth streaming and gaming.",
    "rating": 4.4,
    "price": 139.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-018",
    "name": "Nimbus Mesh Node",
    "brand": "Nimbus",
    "category": "Networking",
    "imageUrl": "https://picsum.photos/seed/device18/512/512",
    "description": "Mesh Wi‑Fi node that extends coverage to dead zones in your home or office.",
    "rating": 4.3,
    "price": 99.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-019",
    "name": "DataCore NVMe 1TB",
    "brand": "DataCore",
    "category": "Storage",
    "imageUrl": "https://picsum.photos/seed/device19/512/512",
    "description": "PCIe 4.0 NVMe SSD with fast read/write speeds for gaming PCs and workstations.",
    "rating": 4.7,
    "price": 129.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-020",
    "name": "DataCore Portable SSD 2TB",
    "brand": "DataCore",
    "category": "Storage",
    "imageUrl": "https://picsum.photos/seed/device20/512/512",
    "description": "Rugged USB-C portable SSD with 2 TB capacity and hardware encryption.",
    "rating": 4.6,
    "price": 219.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-021",
    "name": "VisionPro 24 Webcam",
    "brand": "VisionPro",
    "category": "Webcam",
    "imageUrl": "https://picsum.photos/seed/device21/512/512",
    "description": "Full HD webcam with privacy shutter and flexible mounting options.",
    "rating": 4.1,
    "price": 49.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-022",
    "name": "VisionPro Conference Cam",
    "brand": "VisionPro",
    "category": "Webcam",
    "imageUrl": "https://picsum.photos/seed/device22/512/512",
    "description": "Wide-angle conference webcam with stereo mics suited for meeting rooms.",
    "rating": 4.3,
    "price": 179.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-023",
    "name": "Orbit Watch Active",
    "brand": "Orbit",
    "category": "Smartwatch",
    "imageUrl": "https://picsum.photos/seed/device23/512/512",
    "description": "Fitness-focused smartwatch with heart-rate tracking and GPS.",
    "rating": 4.2,
    "price": 199.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-024",
    "name": "Orbit Watch Pro LTE",
    "brand": "Orbit",
    "category": "Smartwatch",
    "imageUrl": "https://picsum.photos/seed/device24/512/512",
    "description": "Premium smartwatch with LTE, AMOLED display, and advanced health metrics.",
    "rating": 4.4,
    "price": 299.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-025",
    "name": "SlateTab 11",
    "brand": "SlateTech",
    "category": "Tablet",
    "imageUrl": "https://picsum.photos/seed/device25/512/512",
    "description": "11-inch tablet with stylus support, ideal for note-taking and media.",
    "rating": 4.3,
    "price": 449.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-026",
    "name": "SlateTab Mini 8",
    "brand": "SlateTech",
    "category": "Tablet",
    "imageUrl": "https://picsum.photos/seed/device26/512/512",
    "description": "Compact 8-inch tablet for reading, browsing, and streaming on the go.",
    "rating": 4.2,
    "price": 249.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-027",
    "name": "StreamBox 4K",
    "brand": "StreamBox",
    "category": "Media Player",
    "imageUrl": "https://picsum.photos/seed/device27/512/512",
    "description": "4K streaming box with HDR and voice remote for popular streaming apps.",
    "rating": 4.5,
    "price": 79.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-028",
    "name": "StreamStick HD",
    "brand": "StreamBox",
    "category": "Media Player",
    "imageUrl": "https://picsum.photos/seed/device28/512/512",
    "description": "Compact HDMI streaming stick with full HD output and dual-band Wi‑Fi.",
    "rating": 4.2,
    "price": 49.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-029",
    "name": "GameCore X Console",
    "brand": "GameCore",
    "category": "Game Console",
    "imageUrl": "https://picsum.photos/seed/device29/512/512",
    "description": "Next-gen gaming console with 4K gaming and high-speed SSD.",
    "rating": 4.6,
    "price": 499.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-030",
    "name": "GameCore Handheld Go",
    "brand": "GameCore",
    "category": "Game Console",
    "imageUrl": "https://picsum.photos/seed/device30/512/512",
    "description": "Portable gaming handheld with a 7-inch display and cloud gaming support.",
    "rating": 4.3,
    "price": 349.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-031",
    "name": "HomeSense Smart Bulb",
    "brand": "HomeSense",
    "category": "Smart Home",
    "imageUrl": "https://picsum.photos/seed/device31/512/512",
    "description": "Color-changing smart bulb controllable via app and voice assistants.",
    "rating": 4.4,
    "price": 24.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-032",
    "name": "HomeSense Smart Plug",
    "brand": "HomeSense",
    "category": "Smart Home",
    "imageUrl": "https://picsum.photos/seed/device32/512/512",
    "description": "Wi‑Fi smart plug to schedule and control devices remotely.",
    "rating": 4.3,
    "price": 19.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-033",
    "name": "HomeSense Cam Indoor",
    "brand": "HomeSense",
    "category": "Security Camera",
    "imageUrl": "https://picsum.photos/seed/device33/512/512",
    "description": "Indoor security camera with night vision and motion alerts.",
    "rating": 4.2,
    "price": 59.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-034",
    "name": "HomeSense Cam Outdoor",
    "brand": "HomeSense",
    "category": "Security Camera",
    "imageUrl": "https://picsum.photos/seed/device34/512/512",
    "description": "Weather-resistant outdoor camera with two-way audio and spotlight.",
    "rating": 4.3,
    "price": 129.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-035",
    "name": "ProDock USB-C Hub",
    "brand": "ProDock",
    "category": "Docking Station",
    "imageUrl": "https://picsum.photos/seed/device35/512/512",
    "description": "USB-C hub with HDMI, USB-A, and SD card slots for laptops.",
    "rating": 4.4,
    "price": 79.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-036",
    "name": "ProDock 12-in-1",
    "brand": "ProDock",
    "category": "Docking Station",
    "imageUrl": "https://picsum.photos/seed/device36/512/512",
    "description": "Full desktop docking station with dual 4K display support.",
    "rating": 4.5,
    "price": 169.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-037",
    "name": "EchoPen Stylus Pro",
    "brand": "EchoPen",
    "category": "Stylus",
    "imageUrl": "https://picsum.photos/seed/device37/512/512",
    "description": "Rechargeable stylus with palm rejection for tablets and touchscreens.",
    "rating": 4.2,
    "price": 39.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-038",
    "name": "EchoPen Artist",
    "brand": "EchoPen",
    "category": "Stylus",
    "imageUrl": "https://picsum.photos/seed/device38/512/512",
    "description": "Pressure-sensitive stylus designed for digital artists and note-takers.",
    "rating": 4.3,
    "price": 69.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-039",
    "name": "ClearView HD Projector",
    "brand": "ClearView",
    "category": "Projector",
    "imageUrl": "https://picsum.photos/seed/device39/512/512",
    "description": "1080p home projector with built-in speakers and HDMI input.",
    "rating": 4.1,
    "price": 299.99,
    "currency": "USD"
  },
  {
    "productId": "DEV-040",
    "name": "ClearView 4K Cinema",
    "brand": "ClearView",
    "category": "Projector",
    "imageUrl": "https://picsum.photos/seed/device40/512/512",
    "description": "4K HDR projector with high brightness for home theater setups.",
    "rating": 4.4,
    "price": 899.99,
    "currency": "USD"
  }
]
